services:
  proxy:
    image: caddy:2.9.1-alpine
    container_name: proxy
    ports:
      - "4200:80"
    environment:
      BACKEND_HOST: https://caddy-proxy-production-d923.up.railway.app
      FRONTEND_HOST: http://app
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app
  app:
    container_name: app
    build: .
