version: "3.7"

services:
  proxy:
    container_name: proxy
    build: .
    environment:
      BUDGET_API_HOST: https://budget-production-41ba.up.railway.app
      BUDGET_API_PORT: 443
    ports:
      - "4200:80"
